default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: gp-dev

test:
  <<: *default
  database: gp-testing

production:
  <<: *default
  database: gp-prod
